# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\a6q\IMES_layout_0.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(900, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.electrical_frame = QtWidgets.QGroupBox(self.centralwidget)
        self.electrical_frame.setGeometry(QtCore.QRect(50, 20, 171, 241))
        self.electrical_frame.setObjectName("electrical_frame")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.electrical_frame)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 110, 121, 42))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.measure_iv_box = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.measure_iv_box.setObjectName("measure_iv_box")
        self.verticalLayout.addWidget(self.measure_iv_box)
        self.measure_cv_box = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.measure_cv_box.setObjectName("measure_cv_box")
        self.verticalLayout.addWidget(self.measure_cv_box)
        self.formLayoutWidget = QtWidgets.QWidget(self.electrical_frame)
        self.formLayoutWidget.setGeometry(QtCore.QRect(10, 20, 131, 93))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout_bias = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout_bias.setLabelAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.formLayout_bias.setContentsMargins(0, 0, 0, 0)
        self.formLayout_bias.setHorizontalSpacing(6)
        self.formLayout_bias.setObjectName("formLayout_bias")
        self.initial_bias_label = QtWidgets.QLabel(self.formLayoutWidget)
        self.initial_bias_label.setObjectName("initial_bias_label")
        self.formLayout_bias.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.initial_bias_label)
        self.final_bias_label = QtWidgets.QLabel(self.formLayoutWidget)
        self.final_bias_label.setObjectName("final_bias_label")
        self.formLayout_bias.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.final_bias_label)
        self.voltage_steps_label = QtWidgets.QLabel(self.formLayoutWidget)
        self.voltage_steps_label.setObjectName("voltage_steps_label")
        self.formLayout_bias.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.voltage_steps_label)
        self.voltage_steps = QtWidgets.QSpinBox(self.formLayoutWidget)
        self.voltage_steps.setMinimum(1)
        self.voltage_steps.setMaximum(1000000)
        self.voltage_steps.setProperty("value", 10)
        self.voltage_steps.setObjectName("voltage_steps")
        self.formLayout_bias.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.voltage_steps)
        self.final_bias = QtWidgets.QDoubleSpinBox(self.formLayoutWidget)
        self.final_bias.setDecimals(3)
        self.final_bias.setMinimum(-60.0)
        self.final_bias.setMaximum(60.0)
        self.final_bias.setSingleStep(0.01)
        self.final_bias.setProperty("value", 0.01)
        self.final_bias.setObjectName("final_bias")
        self.formLayout_bias.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.final_bias)
        self.initial_bias = QtWidgets.QDoubleSpinBox(self.formLayoutWidget)
        self.initial_bias.setDecimals(3)
        self.initial_bias.setMinimum(-60.0)
        self.initial_bias.setMaximum(60.0)
        self.initial_bias.setSingleStep(0.01)
        self.initial_bias.setProperty("value", -0.01)
        self.initial_bias.setObjectName("initial_bias")
        self.formLayout_bias.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.initial_bias)
        self.measure_electrical = QtWidgets.QPushButton(self.electrical_frame)
        self.measure_electrical.setGeometry(QtCore.QRect(20, 170, 75, 23))
        self.measure_electrical.setAutoDefault(False)
        self.measure_electrical.setFlat(False)
        self.measure_electrical.setObjectName("measure_electrical")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(30, 290, 271, 141))
        self.textBrowser.setObjectName("textBrowser")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 900, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.electrical_frame.setTitle(_translate("MainWindow", "Electrical"))
        self.measure_iv_box.setText(_translate("MainWindow", "Measure I-V"))
        self.measure_cv_box.setText(_translate("MainWindow", "Measure C-V"))
        self.initial_bias_label.setText(_translate("MainWindow", "Initial bias (V)"))
        self.final_bias_label.setText(_translate("MainWindow", "Final bias (V)"))
        self.voltage_steps_label.setText(_translate("MainWindow", "Voltage steps"))
        self.measure_electrical.setText(_translate("MainWindow", "Measure"))

