function [fitresult, gof] = createFit(s, amp)
%CREATEFIT(S,AMP)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : s
%      Y Output: amp
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 19-Nov-2015 16:46:27


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( s, amp );

% Set up fittype and options.
ft = fittype( 'A*exp(-x./tau).*sin(2*pi*f.*x+phi)', 'independent', 'x', 'dependent', 'y' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.Lower = [0 4500000 -10 0];
opts.StartPoint = [0.257508254123736 0.840717255983663 0.254282178971531 0.814284826068816];
opts.Upper = [100 4900000 10 4e-06];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'untitled fit 1' );
h = plot( fitresult, xData, yData );
legend( h, 'amp vs. s', 'untitled fit 1', 'Location', 'NorthEast' );
% Label axes
xlabel s
ylabel amp
grid on


