function [fitresult, gof] = createFit1(pixelnumber, Icolumn1)
%CREATEFIT1(PIXELNUMBER,ICOLUMN1)
%  Create a fit.
%
%  Data for 'Gausss CNT fit' fit:
%      X Input : pixelnumber
%      Y Output: Icolumn1
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 15-Apr-2016 10:03:32


%% Fit: 'Gausss CNT fit'.
Xvar = pixelnumber;     %input x data
Yvar = Icolumn1;        %input y data


[xData, yData] = prepareCurveData(Xvar, Yvar);

% Set up fittype and options.
ft = fittype( 'gauss8' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.Lower = [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0];
opts.StartPoint = [251 66 12.9399038849393 171.343891755542 89 20.3848242321851 169.327617517717 34 28.7943277331627 167.999924867436 167 20.0322334038051 167 458 18.3478183128687 161.999999999999 282 10.2986481060411 143.466360077877 303 12.7841873395802 137.999809896395 243 17.4516975802209];
opts.Upper = [250 213 206 250 513 206 250 513 206 250 513 206 250 513 206 250 513 206 250 513 206 250 513 206];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );


S = max(Xvar)
M = mean(Yvar)



% Plot fit with data.
figure( 'Name', 'Gausss CNT fit' );
h = plot( fitresult, xData, yData );
legend( h, 'Icolumn1 vs. pixelnumber', 'Gausss CNT fit', 'Location', 'NorthEast' );
% Label axes
xlabel pixelnumber
ylabel Icolumn1



